<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA4oB1pM\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA4oB1pM/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerA4oB1pM.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerA4oB1pM\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerA4oB1pM\appAppKernelProdContainer([
    'container.build_hash' => 'A4oB1pM',
    'container.build_id' => '618425d5',
    'container.build_time' => 1699870186,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA4oB1pM');
